version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
      - sudo apt-get update
      - sudo apt-get install nginx -y
  pre_build:
    commands:
      - echo Preparing build environment
  build:
    commands:
      - echo Build started on `date`
      - echo Copying source files to Nginx directory
      - sudo cp index.html /var/www/html/
  post_build:
    commands:
      - echo Configuring Nginx
      - sudo systemctl start nginx
      - sudo systemctl enable nginx

artifacts:
  files:
    - index.html
