version: 0.2

phases:
  install:
    commands:
      - echo "Starting install phase"
      - sudo apt-get clean
      - sudo apt-get update -y || (echo "apt-get update failed" && exit 1)
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo "Starting build phase"
      - cp index.html /var/www/html/

artifacts:
  files:
    - /var/www/html/index.html

